version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/
    # volume name is react_build
    # put everything in /react/build into our volume
    volumes:
      - react_build:/react/build
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    # for hot reload
    environment:
      CHOKIDAR_USEPOLLING: "true"
    # so it won't stop running
    stdin_open: true

  backend:
    # restart: always
    build: 
      context: ./mychatroom/
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn mychatroom.wsgi --bind 0.0.0.0:8000

  nginx:
    image: nginx:latest
    # translate request from 80(default port) to 8080(port nginx listens)
    ports: 
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    # defined running order
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
