version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - .:/react
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start