version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - .:/react
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start

  backend:
    restart: always
    build: 
      context: ./mychatroom/
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000