# Generated by Django 4.0.4 on 2022-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_message_options_alter_topic_name_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
